package com.example.recipebook.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF9)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFFBFDF9)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DD)
val md_theme_light_onSurfaceVariant = Color(0xFF404943)
val md_theme_light_outline = Color(0xFF707973)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1ED)
val md_theme_light_inverseSurface = Color(0xFF2E312F)
val md_theme_light_inversePrimary = Color(0xFF6CDBAC)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006C4C)
val md_theme_light_outlineVariant = Color(0xFFBFC9C2)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DF)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DF)
val md_theme_dark_surfaceVariant = Color(0xFF404943)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C2)
val md_theme_dark_outline = Color(0xFF8A938C)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1A)
val md_theme_dark_inverseSurface = Color(0xFFE1E3DF)
val md_theme_dark_inversePrimary = Color(0xFF006C4C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF6CDBAC)
val md_theme_dark_outlineVariant = Color(0xFF404943)
val md_theme_dark_scrim = Color(0xFF000000)

// Primary (Light & Dark) - More towards a vibrant purple
val md_theme_light_primary = Color(0xFF9C27B0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0C7F9)
val md_theme_light_onPrimaryContainer = Color(0xFF410070)
val md_theme_dark_primary = Color(0xFFE0C7F9)
val md_theme_dark_onPrimary = Color(0xFF410070)
val md_theme_dark_primaryContainer = Color(0xFF9C27B0)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFFFFF)

// Secondary (Light & Dark) - Lighter shade of purple
val md_theme_light_secondary = Color(0xFFD7BDE2)
val md_theme_light_onSecondary = Color(0xFF370043)
val md_theme_light_secondaryContainer = Color(0xFFF3E5FF)
val md_theme_light_onSecondaryContainer = Color(0xFF6F1B82)
val md_theme_dark_secondary = Color(0xFFBBBDEB)
val md_theme_dark_onSecondary = Color(0xFF6F1B82)
val md_theme_dark_secondaryContainer = Color(0xFFE0C7F9)
val md_theme_dark_onSecondaryContainer = Color(0xFFD7BDE2)

// Tertiary (Light & Dark) - Darker shade of purple
val md_theme_light_tertiary = Color(0xFF7B1FA2)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDDCFFF)
val md_theme_light_onTertiaryContainer = Color(0xFF2C005E)
val md_theme_dark_tertiary = Color(0xFFC59CEF)
val md_theme_dark_onTertiary = Color(0xFF2C005E)
val md_theme_dark_tertiaryContainer = Color(0xFF7B1FA2)
val md_theme_dark_onTertiaryContainer = Color(0xFFDDCFFF)